# Site settings
title: Robert Chen
email: your-email@example.com
description: Dynamic professional with over 10 years of experience as a program manager in the technology sector, specializing in marketing, sales operations, and licensing. Proven ability to lead cross-functional teams and drive projects to success while aligning product development with market needs. Aiming to transition into a product management role where strategic vision and customer insights can foster innovative solutions.
url: "https://robertchenpm.github.io/" # the URL of your GitHub Pages site

# Cayman theme settings
theme: jekyll-theme-cayman

# Author and social settings
author:
  name: Robert Chen
  email: Rec.Chen@gmail.com
  linkedin: https://www.linkedin.com/in/recchen/

# Navigation settings
navigation:
  - Home: /
  - About: /about
  - Projects: /projects
  - Contact: /contact

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - node_modules/
  - vendor/
  - .gitignore
